#!/bin/bash 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/srad_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2016.nc 
